sa_sr_position_controller:
  type: effort_controllers/JointPositionController
  joint: ShoulderJRotate
  pid:
    p: 15.0
    i: 1.0
    d: 5.0
    i_clamp: 30.0

sa_ss_position_controller:
  type: effort_controllers/JointPositionController
  joint: ShoulderJSwing
  pid:
    p: 15.0
    i: 30.0
    d: 10.0
    i_clamp: 90.0

sa_es_position_controller:
  type: effort_controllers/JointPositionController
  joint: ElbowJSwing
  pid:
    p: 30.0
    i: 10.0
    d: 5.0
    i_clamp: 90.0

sa_er_position_controller:
  type: effort_controllers/JointPositionController
  joint: ElbowJRotate
  pid:
    p: 30.0
    i: 3.0
    d: 5.0
    i_clamp: 5.0

r_arm_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ShoulderJRotate
    - ShoulderJSwing
    - ElbowJSwing
    - ElbowJRotate
  gains:
    ShoulderJRotate: {p: 140.0, d: 30.0}
    ShoulderJSwing: {p: 140.0, d: 30.0}
    ElbowJSwing: {p: 140.0, d: 30.0}
    ElbowJRotate: {p: 140.0, d: 30.0}
