controller_list:
  - name: /arm_1/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: /arm1/gripper_controller
    action_ns: position_command
    type: PositionCommand
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
