// Generated by gencpp from file ik/ik.msg
// DO NOT EDIT!


#ifndef IK_MESSAGE_IK_H
#define IK_MESSAGE_IK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ik
{
template <class ContainerAllocator>
struct ik_
{
  typedef ik_<ContainerAllocator> Type;

  ik_()
    : pose()
    , jointvalue()  {
    }
  ik_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , jointvalue(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _jointvalue_type;
  _jointvalue_type jointvalue;




  typedef boost::shared_ptr< ::ik::ik_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ik::ik_<ContainerAllocator> const> ConstPtr;

}; // struct ik_

typedef ::ik::ik_<std::allocator<void> > ik;

typedef boost::shared_ptr< ::ik::ik > ikPtr;
typedef boost::shared_ptr< ::ik::ik const> ikConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ik::ik_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ik::ik_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ik

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ik': ['/home/chao/catkin_ws_action/src/ik/msg', '/home/chao/catkin_ws_action/devel/share/ik/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ik::ik_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ik::ik_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ik::ik_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ik::ik_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ik::ik_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ik::ik_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ik::ik_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1759521e875316328da2b75f3047f9a8";
  }

  static const char* value(const ::ik::ik_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1759521e87531632ULL;
  static const uint64_t static_value2 = 0x8da2b75f3047f9a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ik::ik_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ik/ik";
  }

  static const char* value(const ::ik::ik_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ik::ik_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
float64[]  jointvalue\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ik::ik_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ik::ik_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.jointvalue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ik_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ik::ik_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ik::ik_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "jointvalue[]" << std::endl;
    for (size_t i = 0; i < v.jointvalue.size(); ++i)
    {
      s << indent << "  jointvalue[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointvalue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IK_MESSAGE_IK_H
