// Generated by gencpp from file ik/ik_.msg
// DO NOT EDIT!


#ifndef IK_MESSAGE_IK__H
#define IK_MESSAGE_IK__H

#include <ros/service_traits.h>


#include <ik/ik_Request.h>
#include <ik/ik_Response.h>


namespace ik
{

struct ik_
{

typedef ik_Request Request;
typedef ik_Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ik_
} // namespace ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ik::ik_ > {
  static const char* value()
  {
    return "1759521e875316328da2b75f3047f9a8";
  }

  static const char* value(const ::ik::ik_&) { return value(); }
};

template<>
struct DataType< ::ik::ik_ > {
  static const char* value()
  {
    return "ik/ik_";
  }

  static const char* value(const ::ik::ik_&) { return value(); }
};


// service_traits::MD5Sum< ::ik::ik_Request> should match 
// service_traits::MD5Sum< ::ik::ik_ > 
template<>
struct MD5Sum< ::ik::ik_Request>
{
  static const char* value()
  {
    return MD5Sum< ::ik::ik_ >::value();
  }
  static const char* value(const ::ik::ik_Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::ik::ik_Request> should match 
// service_traits::DataType< ::ik::ik_ > 
template<>
struct DataType< ::ik::ik_Request>
{
  static const char* value()
  {
    return DataType< ::ik::ik_ >::value();
  }
  static const char* value(const ::ik::ik_Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ik::ik_Response> should match 
// service_traits::MD5Sum< ::ik::ik_ > 
template<>
struct MD5Sum< ::ik::ik_Response>
{
  static const char* value()
  {
    return MD5Sum< ::ik::ik_ >::value();
  }
  static const char* value(const ::ik::ik_Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::ik::ik_Response> should match 
// service_traits::DataType< ::ik::ik_ > 
template<>
struct DataType< ::ik::ik_Response>
{
  static const char* value()
  {
    return DataType< ::ik::ik_ >::value();
  }
  static const char* value(const ::ik::ik_Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IK_MESSAGE_IK__H
