// Generated by gencpp from file ik/ikFeedback.msg
// DO NOT EDIT!


#ifndef IK_MESSAGE_IKFEEDBACK_H
#define IK_MESSAGE_IKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ik
{
template <class ContainerAllocator>
struct ikFeedback_
{
  typedef ikFeedback_<ContainerAllocator> Type;

  ikFeedback_()
    : jointfeedback()  {
    }
  ikFeedback_(const ContainerAllocator& _alloc)
    : jointfeedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _jointfeedback_type;
  _jointfeedback_type jointfeedback;




  typedef boost::shared_ptr< ::ik::ikFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ik::ikFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ikFeedback_

typedef ::ik::ikFeedback_<std::allocator<void> > ikFeedback;

typedef boost::shared_ptr< ::ik::ikFeedback > ikFeedbackPtr;
typedef boost::shared_ptr< ::ik::ikFeedback const> ikFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ik::ikFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ik::ikFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ik

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ik': ['/home/chao/catkin_ws_action/src/ik/msg', '/home/chao/catkin_ws_action/devel/share/ik/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ik::ikFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ik::ikFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ik::ikFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ik::ikFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ik::ikFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ik::ikFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ik::ikFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa0dbe635e90facfe574d814d9b43172";
  }

  static const char* value(const ::ik::ikFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa0dbe635e90facfULL;
  static const uint64_t static_value2 = 0xe574d814d9b43172ULL;
};

template<class ContainerAllocator>
struct DataType< ::ik::ikFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ik/ikFeedback";
  }

  static const char* value(const ::ik::ikFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ik::ikFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float64[] jointfeedback\n\
\n\
\n\
";
  }

  static const char* value(const ::ik::ikFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ik::ikFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointfeedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ik::ikFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ik::ikFeedback_<ContainerAllocator>& v)
  {
    s << indent << "jointfeedback[]" << std::endl;
    for (size_t i = 0; i < v.jointfeedback.size(); ++i)
    {
      s << indent << "  jointfeedback[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointfeedback[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IK_MESSAGE_IKFEEDBACK_H
