(cl:defpackage gripper_controller-msg
  (:use )
  (:export
   "<FLOATTYPEACTION>"
   "FLOATTYPEACTION"
   "<FLOATTYPEACTIONRESULT>"
   "FLOATTYPEACTIONRESULT"
   "<FLOATTYPEGOAL>"
   "FLOATTYPEGOAL"
   "<FLOATTYPEACTIONFEEDBACK>"
   "FLOATTYPEACTIONFEEDBACK"
   "<FLOATTYPEACTIONGOAL>"
   "FLOATTYPEACTIONGOAL"
   "<FLOATTYPERESULT>"
   "FLOATTYPERESULT"
   "<FLOATTYPEFEEDBACK>"
   "FLOATTYPEFEEDBACK"
  ))

