; Auto-generated. Do not edit!


(cl:in-package gripper_controller-msg)


;//! \htmlinclude floattypeFeedback.msg.html

(cl:defclass <floattypeFeedback> (roslisp-msg-protocol:ros-message)
  ((data
    :reader data
    :initarg :data
    :type std_msgs-msg:Float64
    :initform (cl:make-instance 'std_msgs-msg:Float64)))
)

(cl:defclass floattypeFeedback (<floattypeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <floattypeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'floattypeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gripper_controller-msg:<floattypeFeedback> is deprecated: use gripper_controller-msg:floattypeFeedback instead.")))

(cl:ensure-generic-function 'data-val :lambda-list '(m))
(cl:defmethod data-val ((m <floattypeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_controller-msg:data-val is deprecated.  Use gripper_controller-msg:data instead.")
  (data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <floattypeFeedback>) ostream)
  "Serializes a message object of type '<floattypeFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'data) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <floattypeFeedback>) istream)
  "Deserializes a message object of type '<floattypeFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'data) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<floattypeFeedback>)))
  "Returns string type for a message object of type '<floattypeFeedback>"
  "gripper_controller/floattypeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'floattypeFeedback)))
  "Returns string type for a message object of type 'floattypeFeedback"
  "gripper_controller/floattypeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<floattypeFeedback>)))
  "Returns md5sum for a message object of type '<floattypeFeedback>"
  "8d62201b2d01a4931eec14d19d9c5317")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'floattypeFeedback)))
  "Returns md5sum for a message object of type 'floattypeFeedback"
  "8d62201b2d01a4931eec14d19d9c5317")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<floattypeFeedback>)))
  "Returns full string definition for message of type '<floattypeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Float64 data~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'floattypeFeedback)))
  "Returns full string definition for message of type 'floattypeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Float64 data~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <floattypeFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'data))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <floattypeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'floattypeFeedback
    (cl:cons ':data (data msg))
))
