DWAPlannerROS:

  max_vel_x: 0.5 
  min_vel_x: 0.0 

  max_trans_vel: 0.5 
  min_trans_vel: 0.1 
  trans_stopped_vel: 0.1

  max_rot_vel: 3.0 
  min_rot_vel: 0.4  
  rot_stopped_vel: 0.2
  
  acc_lim_x: 0.5 
  acc_lim_theta: 1.0

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2  

  sim_time: 2.0     
  vx_samples: 6       
  vy_samples: 0      
  vtheta_samples: 20 


  path_distance_bias: 64.0      
  goal_distance_bias: 24.0      
  occdist_scale: 0.5         
  forward_point_distance: 0.325 
  stop_time_buffer: 0.2        
  scaling_speed: 0.25          
  max_scaling_factor: 0.2      

  oscillation_reset_dist: 0.1  

  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom

  holonomic_robot: false
