; Auto-generated. Do not edit!


(cl:in-package ik-msg)


;//! \htmlinclude ikFeedback.msg.html

(cl:defclass <ikFeedback> (roslisp-msg-protocol:ros-message)
  ((jointfeedback
    :reader jointfeedback
    :initarg :jointfeedback
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ikFeedback (<ikFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ikFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ikFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ik-msg:<ikFeedback> is deprecated: use ik-msg:ikFeedback instead.")))

(cl:ensure-generic-function 'jointfeedback-val :lambda-list '(m))
(cl:defmethod jointfeedback-val ((m <ikFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ik-msg:jointfeedback-val is deprecated.  Use ik-msg:jointfeedback instead.")
  (jointfeedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ikFeedback>) ostream)
  "Serializes a message object of type '<ikFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'jointfeedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'jointfeedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ikFeedback>) istream)
  "Deserializes a message object of type '<ikFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'jointfeedback) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'jointfeedback)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ikFeedback>)))
  "Returns string type for a message object of type '<ikFeedback>"
  "ik/ikFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ikFeedback)))
  "Returns string type for a message object of type 'ikFeedback"
  "ik/ikFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ikFeedback>)))
  "Returns md5sum for a message object of type '<ikFeedback>"
  "fa0dbe635e90facfe574d814d9b43172")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ikFeedback)))
  "Returns md5sum for a message object of type 'ikFeedback"
  "fa0dbe635e90facfe574d814d9b43172")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ikFeedback>)))
  "Returns full string definition for message of type '<ikFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] jointfeedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ikFeedback)))
  "Returns full string definition for message of type 'ikFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] jointfeedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ikFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'jointfeedback) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ikFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ikFeedback
    (cl:cons ':jointfeedback (jointfeedback msg))
))
