; Auto-generated. Do not edit!


(cl:in-package ik-msg)


;//! \htmlinclude ikResult.msg.html

(cl:defclass <ikResult> (roslisp-msg-protocol:ros-message)
  ((jointresult
    :reader jointresult
    :initarg :jointresult
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ikResult (<ikResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ikResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ikResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ik-msg:<ikResult> is deprecated: use ik-msg:ikResult instead.")))

(cl:ensure-generic-function 'jointresult-val :lambda-list '(m))
(cl:defmethod jointresult-val ((m <ikResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ik-msg:jointresult-val is deprecated.  Use ik-msg:jointresult instead.")
  (jointresult m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ikResult>) ostream)
  "Serializes a message object of type '<ikResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'jointresult))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'jointresult))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ikResult>) istream)
  "Deserializes a message object of type '<ikResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'jointresult) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'jointresult)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ikResult>)))
  "Returns string type for a message object of type '<ikResult>"
  "ik/ikResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ikResult)))
  "Returns string type for a message object of type 'ikResult"
  "ik/ikResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ikResult>)))
  "Returns md5sum for a message object of type '<ikResult>"
  "71015519b9e78e4b859088d8b25e40a6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ikResult)))
  "Returns md5sum for a message object of type 'ikResult"
  "71015519b9e78e4b859088d8b25e40a6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ikResult>)))
  "Returns full string definition for message of type '<ikResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] jointresult~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ikResult)))
  "Returns full string definition for message of type 'ikResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] jointresult~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ikResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'jointresult) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ikResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ikResult
    (cl:cons ':jointresult (jointresult msg))
))
