controller_list:
 - name: "ur5"
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - ur5_arm_shoulder_pan_joint
     - ur5_arm_shoulder_lift_joint
     - ur5_arm_elbow_joint
     - ur5_arm_wrist_1_joint
     - ur5_arm_wrist_2_joint
     - ur5_arm_wrist_3_joint
     - rh_WRJ1
 - name: rh_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - rh_THJ5
     - rh_THJ4
     - rh_THJ2
     - rh_THJ1
     - rh_FFJ4
     - rh_FFJ3
     - rh_FFJ2
     - rh_FFJ1
     - rh_MFJ4
     - rh_MFJ3
     - rh_MFJ2
     - rh_MFJ1
     - rh_RFJ4
     - rh_RFJ3
     - rh_RFJ2
     - rh_RFJ1
