controller_list:
  - name: fake_right_arm_controller
    joints:
      - ur5_arm_shoulder_pan_joint
      - ur5_arm_shoulder_lift_joint
      - ur5_arm_elbow_joint
      - ur5_arm_wrist_1_joint
      - ur5_arm_wrist_2_joint
      - ur5_arm_wrist_3_joint
  - name: fake_right_hand_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_first_finger_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
  - name: fake_rh_middle_finger_controller
    joints:
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
  - name: fake_rh_ring_finger_controller
    joints:
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
  - name: fake_rh_thumb_controller
    joints:
      - rh_THJ5
      - rh_THJ4
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_fingertips_controller
    joints:
      []
  - name: fake_rh_fingers_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_first_finger_thumb_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_middle_finger_thumb_controller
    joints:
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_ring_finger_thumb_controller
    joints:
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ2
      - rh_THJ1