right_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
rh_first_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_fftip
rh_middle_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_mftip
rh_ring_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_rftip
rh_thumb:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  position_only_ik: true
  tip_name: rh_thtip
