set(_CATKIN_CURRENT_PACKAGE "ar_track_alvar")
set(ar_track_alvar_MAINTAINER "Scott Niekum <sniekum@cs.umass.edu>")
set(ar_track_alvar_DEPRECATED "")
set(ar_track_alvar_VERSION "0.5.3")
set(ar_track_alvar_BUILD_DEPENDS "ar_track_alvar_msgs" "cmake_modules" "cv_bridge" "geometry_msgs" "image_transport" "message_generation" "pcl_ros" "pcl_conversions" "resource_retriever" "rospy" "roscpp" "sensor_msgs" "std_msgs" "tf" "tf2" "tinyxml" "visualization_msgs" "dynamic_reconfigure")
set(ar_track_alvar_RUN_DEPENDS "ar_track_alvar_msgs" "cv_bridge" "geometry_msgs" "image_transport" "message_runtime" "pcl_ros" "pcl_conversions" "resource_retriever" "rospy" "roscpp" "sensor_msgs" "std_msgs" "tf" "tf2" "tinyxml" "visualization_msgs" "dynamic_reconfigure")
set(ar_track_alvar_BUILDTOOL_DEPENDS "catkin")