// Generated by gencpp from file realsense_camera/get_rgb_uv.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_GET_RGB_UV_H
#define REALSENSE_CAMERA_MESSAGE_GET_RGB_UV_H

#include <ros/service_traits.h>


#include <realsense_camera/get_rgb_uvRequest.h>
#include <realsense_camera/get_rgb_uvResponse.h>


namespace realsense_camera
{

struct get_rgb_uv
{

typedef get_rgb_uvRequest Request;
typedef get_rgb_uvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_rgb_uv
} // namespace realsense_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_camera::get_rgb_uv > {
  static const char* value()
  {
    return "0eb5e9c6325d1b134d64fc42997917cc";
  }

  static const char* value(const ::realsense_camera::get_rgb_uv&) { return value(); }
};

template<>
struct DataType< ::realsense_camera::get_rgb_uv > {
  static const char* value()
  {
    return "realsense_camera/get_rgb_uv";
  }

  static const char* value(const ::realsense_camera::get_rgb_uv&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_camera::get_rgb_uvRequest> should match 
// service_traits::MD5Sum< ::realsense_camera::get_rgb_uv > 
template<>
struct MD5Sum< ::realsense_camera::get_rgb_uvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::get_rgb_uv >::value();
  }
  static const char* value(const ::realsense_camera::get_rgb_uvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::get_rgb_uvRequest> should match 
// service_traits::DataType< ::realsense_camera::get_rgb_uv > 
template<>
struct DataType< ::realsense_camera::get_rgb_uvRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::get_rgb_uv >::value();
  }
  static const char* value(const ::realsense_camera::get_rgb_uvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_camera::get_rgb_uvResponse> should match 
// service_traits::MD5Sum< ::realsense_camera::get_rgb_uv > 
template<>
struct MD5Sum< ::realsense_camera::get_rgb_uvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::get_rgb_uv >::value();
  }
  static const char* value(const ::realsense_camera::get_rgb_uvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::get_rgb_uvResponse> should match 
// service_traits::DataType< ::realsense_camera::get_rgb_uv > 
template<>
struct DataType< ::realsense_camera::get_rgb_uvResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::get_rgb_uv >::value();
  }
  static const char* value(const ::realsense_camera::get_rgb_uvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_GET_RGB_UV_H
