// Generated by gencpp from file realsense_camera/get_rgb_uvResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_GET_RGB_UVRESPONSE_H
#define REALSENSE_CAMERA_MESSAGE_GET_RGB_UVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_camera
{
template <class ContainerAllocator>
struct get_rgb_uvResponse_
{
  typedef get_rgb_uvResponse_<ContainerAllocator> Type;

  get_rgb_uvResponse_()
    : x_min_uv(0)
    , y_min_uv(0)
    , x_max_uv(0)
    , y_max_uv(0)  {
    }
  get_rgb_uvResponse_(const ContainerAllocator& _alloc)
    : x_min_uv(0)
    , y_min_uv(0)
    , x_max_uv(0)
    , y_max_uv(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_min_uv_type;
  _x_min_uv_type x_min_uv;

   typedef int32_t _y_min_uv_type;
  _y_min_uv_type y_min_uv;

   typedef int32_t _x_max_uv_type;
  _x_max_uv_type x_max_uv;

   typedef int32_t _y_max_uv_type;
  _y_max_uv_type y_max_uv;




  typedef boost::shared_ptr< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_rgb_uvResponse_

typedef ::realsense_camera::get_rgb_uvResponse_<std::allocator<void> > get_rgb_uvResponse;

typedef boost::shared_ptr< ::realsense_camera::get_rgb_uvResponse > get_rgb_uvResponsePtr;
typedef boost::shared_ptr< ::realsense_camera::get_rgb_uvResponse const> get_rgb_uvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'realsense_camera': ['/home/chao/catkin_ws_youbot/src/realsense_camera/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36c20a9a661d32cf44ffca6c6be7e4a2";
  }

  static const char* value(const ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36c20a9a661d32cfULL;
  static const uint64_t static_value2 = 0x44ffca6c6be7e4a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_camera/get_rgb_uvResponse";
  }

  static const char* value(const ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x_min_uv\n\
int32 y_min_uv\n\
int32 x_max_uv\n\
int32 y_max_uv\n\
";
  }

  static const char* value(const ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_min_uv);
      stream.next(m.y_min_uv);
      stream.next(m.x_max_uv);
      stream.next(m.y_max_uv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_rgb_uvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_camera::get_rgb_uvResponse_<ContainerAllocator>& v)
  {
    s << indent << "x_min_uv: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_min_uv);
    s << indent << "y_min_uv: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_min_uv);
    s << indent << "x_max_uv: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_max_uv);
    s << indent << "y_max_uv: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_max_uv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_GET_RGB_UVRESPONSE_H
