// Generated by gencpp from file realsense_camera/realsenseConfig.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_REALSENSECONFIG_H
#define REALSENSE_CAMERA_MESSAGE_REALSENSECONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_camera
{
template <class ContainerAllocator>
struct realsenseConfig_
{
  typedef realsenseConfig_<ContainerAllocator> Type;

  realsenseConfig_()
    : depth_raw_unit(0.0)  {
    }
  realsenseConfig_(const ContainerAllocator& _alloc)
    : depth_raw_unit(0.0)  {
  (void)_alloc;
    }



   typedef float _depth_raw_unit_type;
  _depth_raw_unit_type depth_raw_unit;




  typedef boost::shared_ptr< ::realsense_camera::realsenseConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_camera::realsenseConfig_<ContainerAllocator> const> ConstPtr;

}; // struct realsenseConfig_

typedef ::realsense_camera::realsenseConfig_<std::allocator<void> > realsenseConfig;

typedef boost::shared_ptr< ::realsense_camera::realsenseConfig > realsenseConfigPtr;
typedef boost::shared_ptr< ::realsense_camera::realsenseConfig const> realsenseConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_camera::realsenseConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_camera::realsenseConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'realsense_camera': ['/home/chao/catkin_ws_youbot/src/realsense_camera/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_camera::realsenseConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_camera::realsenseConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_camera::realsenseConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78f677fac7365df7ab1d8244f7e2fa95";
  }

  static const char* value(const ::realsense_camera::realsenseConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78f677fac7365df7ULL;
  static const uint64_t static_value2 = 0xab1d8244f7e2fa95ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_camera/realsenseConfig";
  }

  static const char* value(const ::realsense_camera::realsenseConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 depth_raw_unit\n\
";
  }

  static const char* value(const ::realsense_camera::realsenseConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth_raw_unit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct realsenseConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_camera::realsenseConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_camera::realsenseConfig_<ContainerAllocator>& v)
  {
    s << indent << "depth_raw_unit: ";
    Printer<float>::stream(s, indent + "  ", v.depth_raw_unit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_REALSENSECONFIG_H
